from typing import Iterable, Tuple
# Return the sum of even and odd integers in a sequence.

def sum_even_odd(numbers: Iterable[int]) -> Tuple[int, int]:
    """Return the sum of even and odd integers in a sequence.

    Args:
        numbers: An iterable of integers to process.

    Returns:
        A tuple (even_sum, odd_sum) where:
        - even_sum is the sum of all even integers in numbers.
        - odd_sum is the sum of all odd integers in numbers.

    Raises:
        TypeError: If any element in numbers is not an integer.

    Examples:
        >>> sum_even_odd([1, 2, 3, 4, 5])
        (6, 9)
        >>> sum_even_odd([])
        (0, 0)
    """
    even_sum = 0
    odd_sum = 0

    for n in numbers:
        if not isinstance(n, int):
            raise TypeError("All elements must be integers.")
        if n % 2 == 0:
            even_sum += n
        else:
            odd_sum += n

    return even_sum, odd_sum


if __name__ == "__main__":
    sample = [1, 2, 3, 4, 5]
    print(sum_even_odd(sample))  # (6, 9)
    
# This is the docstring generated by COpilot
    """
    Calculate the sum of even and odd numbers in an iterable.

    Iterates through the given iterable of integers and computes the total
    sum of even and odd values separately. Returns a tuple where the first
    element is the sum of even numbers and the second element is the sum
    of odd numbers.

    Args:
        numbers (Iterable[int]): A sequence of integers.

    Returns:
        Tuple[int, int]: A tuple containing the even sum and odd sum.

    Raises:
        TypeError: If the input contains non-integer values.
    """

